import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getCompanyJob, getCompanyJobAnalytics } from '../../Services/companyService';
const text = (v) => v?.replaceAll('_', ' ') || '—';
export default function CompanyJobDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [job, setJob] = useState(null); const [analytics, setAnalytics] = useState(null); const [error, setError] = useState('');
  useEffect(() => { Promise.all([getCompanyJob(id), getCompanyJobAnalytics(id)]).then(([jobData, analyticsData]) => { setJob(jobData); setAnalytics(analyticsData); }).catch((e) => setError(e.response?.data?.message || 'Could not load job.')); }, [id]);
  if (error) return <p className="table-message error">{error}</p>; if (!job) return <p className="table-message">Loading job…</p>;
  return <div className="admin-page"><header className="admin-header"><div><p className="eyebrow">Job details</p><h1>{job.title}</h1></div><div className="modal-actions"><button onClick={() => navigate('/company/jobs')}>← Back</button><button className="primary-button" onClick={() => navigate(`/company/jobs/${id}/edit`)}>Edit job</button></div></header><section className="metric-grid job-stats"><article className="metric-card"><div className="metric-copy plain"><span>Unique views</span><strong>{analytics?.uniqueViewers ?? job.uniqueViewers ?? 0}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Applications</span><strong>{analytics?.totalApplications ?? 0}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Admitted</span><strong className="tone-green">{analytics?.admittedApplications ?? 0}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Rejected</span><strong className="tone-red">{analytics?.rejectedApplications ?? 0}</strong></div></article></section><section className="panel detail-panel"><div className="detail-meta"><span className="status-badge">{text(job.status)}</span><span>{text(job.employmentType)}</span><span>{job.location || 'Location not specified'}</span><span>{job.experienceRequired ?? 0} years experience</span></div><h2>Description</h2><p className="detail-copy">{job.description}</p><h2>Requirements</h2><p className="detail-copy">{job.requirements || 'No requirements provided.'}</p><h2>Salary</h2><p>{job.salaryMin || job.salaryMax ? `${job.salaryMin || '—'} - ${job.salaryMax || '—'}` : 'Not specified'}</p><button className="primary-button" onClick={() => navigate(`/company/applications?jobId=${id}`)}>View applications</button></section></div>;
}
