package com.hirena.job.entity;

public enum JobCategory {
    FRONTEND, BACKEND, FULL_STACK, CLOUD_DEVOPS, SOFTWARE_ENGINEERING,
    DATA_AI, UI_UX_DESIGN, QA_TESTING, IT_HELP_DESK, CYBERSECURITY,
    SALES, MARKETING, FINANCE, HUMAN_RESOURCES, REAL_ESTATE,
    CUSTOMER_SERVICE, HEALTHCARE, ENGINEERING, EDUCATION, OTHER
}
