import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getCompanyApplication, updateCompanyApplicationStatus } from '../../Services/companyService';
const tone = (v) => v === 'ACCEPTED' ? 'green' : v === 'REJECTED' ? 'red' : v === 'REVIEWING' ? 'blue' : 'orange';
export default function CompanyApplicationDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [app, setApp] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { getCompanyApplication(id).then(setApp).catch((e) => setError(e.response?.data?.message || 'Could not load application.')); }, [id]);
  const update = async (status) => { setSaving(true); setError(''); try { setApp(await updateCompanyApplicationStatus(id, status)); } catch (e) { setError(e.response?.data?.message || 'Could not update application.'); } finally { setSaving(false); } };
  if (error && !app) return <p className="table-message error">{error}</p>; if (!app) return <p className="table-message">Loading application…</p>;
  return <div className="admin-page"><header className="admin-header"><div><p className="eyebrow">Applications</p><h1>Application details</h1></div><button onClick={() => navigate('/company/applications')}>← Back</button></header><section className="panel detail-panel"><span className={`status-badge ${tone(app.status)}`}>{app.status}</span><div className="metric-grid"><article className="metric-card"><div className="metric-copy plain"><span>Candidate</span><strong>{app.jobSeekerFirstName} {app.jobSeekerLastName}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Email</span><strong>{app.jobSeekerEmail}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Applied for</span><strong>{app.jobTitle}</strong></div></article><article className="metric-card"><div className="metric-copy plain"><span>Applied at</span><strong>{app.appliedAt ? new Date(app.appliedAt).toLocaleDateString() : '—'}</strong></div></article></div><h2>Cover letter</h2><p className="detail-copy">{app.coverLetter || 'No cover letter provided.'}</p>{error && <p className="table-message error">{error}</p>}{app.status !== 'ACCEPTED' && app.status !== 'REJECTED' && <div className="modal-actions"><button disabled={saving} onClick={() => update('REJECTED')} className="danger-button">Reject</button><button disabled={saving} onClick={() => update('ACCEPTED')} className="primary-button">Accept application</button></div>}</section></div>;
}
