import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { getCompanyApplications } from '../../Services/companyService';
const tone = (v) => v === 'ACCEPTED' ? 'green' : v === 'REJECTED' ? 'red' : v === 'REVIEWING' ? 'blue' : 'orange';
export default function CompanyApplications() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [apps, setApps] = useState([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getCompanyApplications().then(setApps).catch((e) => setError(e.response?.data?.message || 'Could not load applications.')); }, []);
  const filtered = apps.filter((a) => (!status || a.status === status) && (!params.get('jobId') || String(a.jobId) === params.get('jobId')) && `${a.jobSeekerFirstName} ${a.jobSeekerLastName} ${a.jobTitle}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="admin-page"><header className="admin-header"><div><p className="eyebrow">Pipeline</p><h1>Applications</h1></div></header><section className="panel table-panel"><div className="filters-row"><div className="search-box"><span>⌕</span><input placeholder="Search candidate or job..." value={query} onChange={(e) => setQuery(e.target.value)} /></div><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Status: All</option>{['PENDING','REVIEWING','ACCEPTED','REJECTED'].map((v) => <option key={v}>{v}</option>)}</select></div>{error && <p className="table-message error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>CANDIDATE</th><th>JOB</th><th>STATUS</th><th>APPLIED AT</th><th>ACTION</th></tr></thead><tbody>{filtered.map((app) => <tr key={app.id}><td><strong>{app.jobSeekerFirstName} {app.jobSeekerLastName}</strong><br /><small>{app.jobSeekerEmail}</small></td><td>{app.jobTitle}</td><td><span className={`status-badge ${tone(app.status)}`}>{app.status}</span></td><td>{app.appliedAt ? new Date(app.appliedAt).toLocaleDateString() : '—'}</td><td><button onClick={() => navigate(`/company/applications/${app.id}`)}>View</button></td></tr>)}</tbody></table>{!filtered.length && <p className="table-message">No applications match your filters.</p>}</div></section></div>;
}
