export const COMPANY_INDUSTRIES = [
  ['Information Technology', 'Information Technology'],
  ['Financial Services', 'Financial Services'],
  ['Telecommunications', 'Telecommunications'],
  ['Media & Advertising', 'Media & Advertising'],
  ['Manufacturing', 'Manufacturing'],
  ['E-commerce', 'E-commerce'],
  ['Logistics & Transport', 'Logistics & Transport'],
  ['Logistics & Supply Chain', 'Logistics & Supply Chain'],
  ['Healthcare', 'Healthcare'],
  ['Energy', 'Energy'],
  ['Automotive', 'Automotive'],
  ['Education', 'Education'],
  ['Hospitality', 'Hospitality'],
  ['Agriculture', 'Agriculture'],
  ['Finance', 'Finance'],
  ['Construction', 'Construction'],
  ['Real Estate', 'Real Estate'],
  ['Retail', 'Retail'],
  ['Media & Entertainment', 'Media & Entertainment'],
];
